apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-ram
  namespace: my-secure-namespace # specify the namespace here
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: test08111997.jfrog.io/docker-trial/nginx-ram:sig
  imagePullSecrets:
  - name: regcred2

