apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-nginx-attest
  namespace: my-secure-namespace # specify the namespace here
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: test08111997.jfrog.io/docker-trial/nginx-attest:sig
  imagePullSecrets:
  - name: regcred2  # no namespace specified here
